dist: bionic
language: python
python:
- "3.6"
compiler:
- gcc
addons:
  apt:
    packages:
    - valac
    - uuid-dev
    - libevent-dev
    - libarchive-dev
    - intltool
    - libjansson-dev
    - libonig-dev
    - libfuse-dev
    - net-tools
before_install:
  - chmod +x ci/install-deps.sh
  - chmod +x ci/functests.sh
  - pip install -r ./ci/requirements.txt
install:
- "./ci/install-deps.sh"
script:
- "./ci/functests.sh init && ./ci/functests.sh runserver && ./ci/functests.sh test"
